<?xml version="1.0" encoding="utf-8"?><Database Name="DemoDB" Class="DemoExampleLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.TestModels" Member="TestModels">
    <Type Name="TestModel">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>